export async function GET() {
  const products = [
    {
      id: "001",
      name: "Table Lamp",
      price: 58,
      category: "Home decor",
      image: "/images/product_img1.png",
      stock: 5,
      hotItem: false,
    },
    {
      id: "002",
      name: "Speaker Gray",
      price: 42,
      category: "Audio",
      image: "/images/product_img2.png",
      stock: 8,
      hotItem: true,
    },
    {
      id: "003",
      name: "Watch White",
      price: 26,
      category: "Watch",
      image: "/images/product_img3.png",
      stock: 3,
      hotItem: false,
    },
    {
      id: "004",
      name: "White Headphone",
      price: 29,
      category: "Audio",
      image: "/images/product_img4.png",
      stock: 4,
      hotItem: false,
    },
    {
      id: "005",
      name: "Speaker Black",
      price: 98,
      category: "Audio",
      image: "/images/product_img5.png",
      stock: 5,
      hotItem: true,
    },
    {
      id: "006",
      name: "Security Camera",
      price: 23,
      category: "Security",
      image: "/images/product_img6.png",
      stock: 7,
      hotItem: false,
    },
    {
      id: "007",
      name: "Pen for iPad",
      price: 32,
      category: "Accessories",
      image: "/images/product_img7.png",
      stock: 2,
      hotItem: false,
    },
    {
      id: "008",
      name: "Home Theater",
      price: 20,
      category: "Audio",
      image: "/images/product_img8.png",
      stock: 8,
      hotItem: true,
    },
    {
      id: "009",
      name: "Wireless Earbuds",
      price: 47,
      category: "Audio",
      image: "/images/product_img9.png",
      stock: 11,
      hotItem: true,
    },
    {
      id: "0010",
      name: "Smart Watch",
      price: 97,
      category: "Watch",
      image: "/images/product_img10.png",
      stock: 4,
      hotItem: false,
    },
    {
      id: "0011",
      name: "Gaming Mouse",
      price: 36,
      category: "Accessories",
      image: "/images/product_img11.png",
      stock: 8,
      hotItem: true,
    },
    {
      id: "0012",
      name: "Home Cleaner",
      price: 27,
      category: "Accessories",
      image: "/images/product_img12.png",
      stock: 6,
      hotItem: false,
    },
  ];

  return Response.json(products);
}
