export async function GET() {
  const products = [
    {
      id: "001",
      name: "Modern Table Lamp",
      price: 29,
      category: "Decoration",
      image: "/images/product_img1.png",
      stock: 5,
    },
    {
      id: "002",
      name: "Smart Speaker Gray",
      price: 29,
      category: "Speakers",
      image: "/images/product_img2.png",
      stock: 8,
    },
    {
      id: "003",
      name: "Smart Watch White",
      price: 29,
      category: "Watch",
      image: "/images/product_img3.png",
      stock: 3,
    },
    {
      id: "004",
      name: "Wireless Headphones",
      price: 29,
      category: "Headphones",
      image: "/images/product_img4.png",
      stock: 4,
    },
    {
      id: "005",
      name: "Smart Watch Black",
      price: 29,
      category: "Watch",
      image: "/images/product_img5.png",
      stock: 5,
    },
    {
      id: "006",
      name: "Security Camera",
      price: 29,
      category: "Camera",
      image: "/images/product_img6.png",
      stock: 7,
    },
    {
      id: "007",
      name: "Smart Pen for iPad",
      price: 29,
      category: "Pen",
      image: "/images/product_img7.png",
      stock: 2,
    },
    {
      id: "008",
      name: "Home Theater",
      price: 29,
      category: "Theater",
      image: "/images/product_img8.png",
      stock: 8,
    },
    {
      id: "009",
      name: "Apple Wireless Earbuds",
      price: 29,
      category: "Earbuds",
      image: "/images/product_img9.png",
      stock: 11,
    },
    {
      id: "0010",
      name: "Apple Smart Watch",
      price: 29,
      category: "Watch",
      image: "/images/product_img10.png",
      stock: 4,
    },
    {
      id: "0011",
      name: "RGB Gaming Mouse",
      price: 29,
      category: "Mouse",
      image: "/images/product_img11.png",
      stock: 8,
    },
    {
      id: "0012",
      name: "Smart Home Cleaner",
      price: 29,
      category: "Cleaner",
      image: "/images/product_img12.png",
      stock: 6,
    },
  ];

  return Response.json(products);
}
