import { DM_Sans } from "next/font/google";
import "../style/index.css";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AppContextProvider } from "@/contexts/AppContext";

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "FED25 Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} text-customBlack antialiased overflow-x-hidden`}
      >
        <AppContextProvider>
          <NextAuthSessionProvider>
            <Navbar />
            <main className="grow">{children}</main>
            <Footer />
          </NextAuthSessionProvider>
        </AppContextProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
